import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

/**
 * Contexto do Copilot:
 * E-commerce de PDFs (Next.js, TS, Tailwind, Shadcn, Drizzle, Auth.js).
 * Requisitos: migração WooCommerce, phpass rehash, PDFs privados, cupons,
 * CMS embutido, notificações externas, afiliados, traduções, SEO/301, PWA opcional.
 * Padrões: acessibilidade, idempotência, validação com Zod.
 */

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"], // Add desired weights
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
